# Generated by Django 6.0.6 on 2026-07-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
